import type { User, Store, Product, Category, Plan, Testimonial } from './types'

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Ropa' },
  { id: 'cat-2', name: 'Accesorios' },
  { id: 'cat-3', name: 'Electrónica' },
  { id: 'cat-4', name: 'Hogar' },
  { id: 'cat-5', name: 'Belleza' },
  { id: 'cat-6', name: 'Deportes' },
  { id: 'cat-7', name: 'Alimentos' },
  { id: 'cat-8', name: 'Juguetes' },
]

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Gratis',
    price: 0,
    description: 'Perfecto para comenzar',
    features: [
      'Hasta 10 productos',
      '1 tienda online',
      'Plantilla básica',
      'Botón de WhatsApp',
      'Soporte por email',
    ],
    productLimit: 10,
    isPopular: false,
    icon: 'Gift',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 29.9,
    description: 'Para tiendas en crecimiento',
    features: [
      'Hasta 100 productos',
      '1 tienda online',
      'Todas las plantillas',
      'Botón de WhatsApp',
      'Dominio personalizado',
      'Estadísticas avanzadas',
      'Soporte prioritario',
    ],
    productLimit: 100,
    isPopular: true,
    icon: 'Zap',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 59.9,
    description: 'Para negocios establecidos',
    features: [
      'Productos ilimitados',
      'Hasta 3 tiendas',
      'Todas las plantillas',
      'Botón de WhatsApp',
      'Dominio personalizado',
      'Estadísticas avanzadas',
      'Soporte 24/7',
      'Personalización total',
      'Sin marca TiendApp',
    ],
    productLimit: -1,
    isPopular: false,
    icon: 'Crown',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'María Demo',
    role: 'Dueña de Dulce María Bakery',
    storeName: 'Dulce María Bakery',
    comment: 'TiendApp me permitió llevar mi panadería al mundo digital en menos de una hora. ¡Mis pedidos aumentaron un 200% en el primer mes!',
    rating: 5,
    avatar: '👩‍💼',
  },
  {
    id: 't2',
    name: 'Juan Delgado',
    role: 'Dueño de Pizzería Napoli',
    storeName: 'Pizzería Napoli',
    comment: 'La integración con WhatsApp es increíble. Mis clientes pueden hacer pedidos directamente por chat. El soporte es excelente.',
    rating: 5,
    avatar: '👨‍🍳',
  },
  {
    id: 't3',
    name: 'Ana Torres',
    role: 'Diseñadora',
    storeName: 'Boutique Élégance',
    comment: 'Las plantillas son hermosas y muy fáciles de personalizar. No necesito saber programación para tener una tienda profesional.',
    rating: 5,
    avatar: '👩‍🎨',
  },
  {
    id: 't4',
    name: 'Carlos Mendoza',
    role: 'Emprendedor',
    storeName: 'TechStore Peru',
    comment: 'Empecé con el plan gratis y en 2 semanas ya migre a Pro. La diferencia en las herramientas es enorme. Totalmente recomendado.',
    rating: 5,
    avatar: '👨‍💻',
  },
  {
    id: 't5',
    name: 'Lucía Ramírez',
    role: 'Artesana',
    storeName: 'Artesanías Ana',
    comment: 'Vendo mis artesanías en todo el país gracias a TiendApp. La plataforma es intuitiva y el precio muy accesible para emprendedores.',
    rating: 5,
    avatar: '👩‍🍳',
  },
  {
    id: 't6',
    name: 'Diego Vargas',
    role: 'CEO',
    storeName: 'DV Electronics',
    comment: 'Migramos desde otra plataforma y el proceso fue súper sencillo. El equipo de soporte nos ayudó en todo momento. Excelente servicio.',
    rating: 5,
    avatar: '👨‍🔧',
  },
]

export const MOCK_USERS: User[] = [
  {
    id: 'user-admin-1',
    name: 'Super Admin',
    email: 'admin@tiendapp.com',
    password: '[HASHED_BCRYPT]',
    role: 'admin',
    planId: 'premium',
    storeId: null,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'user-1',
    name: 'María Demo',
    email: 'tienda@demo.com',
    password: '[HASHED_BCRYPT]',
    role: 'owner',
    planId: 'pro',
    storeId: 'store-1',
    isActive: true,
    createdAt: '2024-03-15T10:00:00.000Z',
  },
  {
    id: 'user-2',
    name: 'Juan Delgado',
    email: 'juan@pizzeria.com',
    password: '[HASHED_BCRYPT]',
    role: 'owner',
    planId: 'pro',
    storeId: 'store-2',
    isActive: true,
    createdAt: '2024-05-20T14:30:00.000Z',
  },
  {
    id: 'user-3',
    name: 'Ana Torres',
    email: 'ana@boutique.com',
    password: '[HASHED_BCRYPT]',
    role: 'owner',
    planId: 'premium',
    storeId: 'store-3',
    isActive: true,
    createdAt: '2024-06-10T09:15:00.000Z',
  },
  {
    id: 'user-4',
    name: 'Carlos Mendoza',
    email: 'carlos@tech.com',
    password: '[HASHED_BCRYPT]',
    role: 'owner',
    planId: 'free',
    storeId: 'store-4',
    isActive: true,
    createdAt: '2024-07-01T16:45:00.000Z',
  },
]

export const MOCK_STORES: Store[] = [
  {
    id: 'store-1',
    name: 'Dulce María Bakery',
    slug: 'dulce-maria-bakery',
    description: 'Los mejores pasteles y panes artesanales de la ciudad. Horneados con amor cada día.',
    logo: '🧁',
    categoryId: 'cat-7',
    planId: 'pro',
    colors: { primary: '#e8a0bf', secondary: '#ba6b8f' },
    whatsappNumber: '+51999990001',
    template: 'moderna',
    bannerUrl: '',
    userId: 'user-1',
    isActive: true,
    createdAt: '2024-03-15T10:00:00.000Z',
  },
  {
    id: 'store-2',
    name: 'Pizzería Napoli',
    slug: 'pizzeria-napoli',
    description: 'Auténtica pizza italiana con ingredientes importados. Masa artesanal horneada a leña.',
    logo: '🍕',
    categoryId: 'cat-7',
    planId: 'pro',
    colors: { primary: '#d32f2f', secondary: '#ff6659' },
    whatsappNumber: '+51999990002',
    template: 'vibrante',
    bannerUrl: '',
    userId: 'user-2',
    isActive: true,
    createdAt: '2024-05-20T14:30:00.000Z',
  },
  {
    id: 'store-3',
    name: 'Boutique Élégance',
    slug: 'boutique-elegance',
    description: 'Moda y accesorios de alta calidad para hombres y mujeres. Elegancia en cada detalle.',
    logo: '👗',
    categoryId: 'cat-1',
    planId: 'premium',
    colors: { primary: '#1a1a2e', secondary: '#c8a456' },
    whatsappNumber: '+51999990003',
    template: 'clasica',
    bannerUrl: '',
    userId: 'user-3',
    isActive: true,
    createdAt: '2024-06-10T09:15:00.000Z',
  },
  {
    id: 'store-4',
    name: 'TechStore Peru',
    slug: 'techstore-peru',
    description: 'Tecnología de última generación al mejor precio. Gadgets, accesorios y más.',
    logo: '💻',
    categoryId: 'cat-3',
    planId: 'free',
    colors: { primary: '#0d47a1', secondary: '#42a5f5' },
    whatsappNumber: '+51999990004',
    template: 'moderna',
    bannerUrl: '',
    userId: 'user-4',
    isActive: true,
    createdAt: '2024-07-01T16:45:00.000Z',
  },
]

export const MOCK_PRODUCTS: Product[] = [
  // Dulce María Bakery products (5)
  { id: 'p1', name: 'Tres Leches Clásico', description: 'Suave bizcocho empapado en tres tipos de leche con merengue italiano.', price: 35.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600', isActive: true, featured: true, rating: 5, storeId: 'store-1', createdAt: '2024-03-20T10:00:00.000Z' },
  { id: 'p2', name: 'Croissant de Mantequilla', description: 'Croissant francés elaborado con mantequilla premium, crujiente por fuera y suave por dentro.', price: 12.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-1', createdAt: '2024-03-21T11:00:00.000Z' },
  { id: 'p3', name: 'Pan de Masa Madre', description: 'Pan artesanal de masa madre con 48 horas de fermentación natural.', price: 18.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-1', createdAt: '2024-03-22T12:00:00.000Z' },
  { id: 'p4', name: 'Cheesecake de Frutos Rojos', description: 'Cheesecake cremoso con coulis de frutos rojos y base de galleta.', price: 42.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600', isActive: true, featured: true, rating: 5, storeId: 'store-1', createdAt: '2024-03-23T13:00:00.000Z' },
  { id: 'p5', name: 'Galletas de Chocolate Artesanales', description: 'Galletas con chispas de chocolate belga y nueces pecan.', price: 8.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600', isActive: true, featured: false, rating: 3, storeId: 'store-1', createdAt: '2024-03-24T14:00:00.000Z' },

  // Pizzería Napoli products (5)
  { id: 'p6', name: 'Margherita Clásica', description: 'Salsa de tomate San Marzano, mozzarella de búfala y albahaca fresca.', price: 38.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600', isActive: true, featured: true, rating: 5, storeId: 'store-2', createdAt: '2024-05-22T10:00:00.000Z' },
  { id: 'p7', name: 'Pepperoni Supreme', description: 'Doble pepperoni, mozzarella fundida y salsa de tomate casera.', price: 42.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-2', createdAt: '2024-05-23T11:00:00.000Z' },
  { id: 'p8', name: 'Quattro Formaggi', description: 'Mozzarella, gorgonzola, parmesano y fontina sobre masa artesanal.', price: 45.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600', isActive: true, featured: true, rating: 5, storeId: 'store-2', createdAt: '2024-05-24T12:00:00.000Z' },
  { id: 'p9', name: 'Prosciutto e Rúcula', description: 'Prosciutto di Parma, rúcula fresca, parmesano y un toque de aceite de oliva.', price: 48.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-2', createdAt: '2024-05-25T13:00:00.000Z' },
  { id: 'p10', name: 'Calzone Italiano', description: 'Masa rellena de mozzarella, jamón, champiñones y salsa de tomate.', price: 40.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1610440042657-612c34d95e9f?w=600', isActive: true, featured: false, rating: 3, storeId: 'store-2', createdAt: '2024-05-26T14:00:00.000Z' },

  // Boutique Élégance products (4)
  { id: 'p11', name: 'Blazer Oversize Negro', description: 'Blazer oversize con corte moderno. Perfecto para cualquier ocasión.', price: 180.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600', isActive: true, featured: true, rating: 5, storeId: 'store-3', createdAt: '2024-06-12T10:00:00.000Z' },
  { id: 'p12', name: 'Vestido Midi Floral', description: 'Vestido midi con estampado floral exclusivo, tejido 100% viscosa.', price: 120.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-3', createdAt: '2024-06-13T11:00:00.000Z' },
  { id: 'p13', name: 'Pantalón Wide Leg Camel', description: 'Pantalón wide leg en tono camel, corte alto y tela fluida.', price: 95.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-3', createdAt: '2024-06-14T12:00:00.000Z' },
  { id: 'p14', name: 'Bufanda de Seda', description: 'Bufanda de seda pura con estampado geométrico italiano.', price: 65.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600', isActive: true, featured: false, rating: 3, storeId: 'store-3', createdAt: '2024-06-15T13:00:00.000Z' },

  // TechStore Peru products (2)
  { id: 'p15', name: 'Auriculares Bluetooth Pro', description: 'Cancelación de ruido activa, 30 horas de batería y sonido Hi-Res.', price: 249.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', isActive: true, featured: true, rating: 5, storeId: 'store-4', createdAt: '2024-07-02T10:00:00.000Z' },
  { id: 'p16', name: 'Cargador Inalámbrico Ultra', description: 'Carga rápida 15W, compatible con todos los dispositivos Qi.', price: 45.0, originalPrice: null, categoryId: '', imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600', isActive: true, featured: false, rating: 4, storeId: 'store-4', createdAt: '2024-07-03T11:00:00.000Z' },
]
